
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 08 18:17:04 CEST 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFERENT = 33;
  public static final int CONST = 19;
  public static final int CONDITIONALEQUAL = 32;
  public static final int CONTINUE = 49;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int FOR = 47;
  public static final int LESS = 36;
  public static final int MINUS = 25;
  public static final int CHARACTER = 39;
  public static final int STATIC = 20;
  public static final int RPAREN = 7;
  public static final int AND = 44;
  public static final int MOREEQUAL = 35;
  public static final int LESSEQUAL = 37;
  public static final int OR = 43;
  public static final int BOOL = 42;
  public static final int COMMA = 8;
  public static final int CLASS = 50;
  public static final int INC = 11;
  public static final int DIV = 23;
  public static final int DIVEQUAL = 30;
  public static final int PLUS = 24;
  public static final int IF = 45;
  public static final int DOT = 21;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 13;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int NUMBER = 38;
  public static final int PLUSEQUAL = 27;
  public static final int MOD = 26;
  public static final int BREAK = 48;
  public static final int IDENT = 40;
  public static final int VOID = 14;
  public static final int ELSE = 46;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 16;
  public static final int READ = 15;
  public static final int RSQUARE = 17;
  public static final int MINUSEQUAL = 28;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 41;
  public static final int PROG = 2;
  public static final int MODEQUAL = 31;
  public static final int DEC = 12;
  public static final int MULEQUAL = 29;
  public static final int PRINT = 9;
  public static final int MORE = 34;
}

